### ISSUE TITLE
Error creaint cluster - storage class inicialisation

### ISSUE THREAD

**Issue by radepal** [kentrikos/terraform-aws-eks#16]
Version: 2.0.0
Terraform 0.11.11
EKS K8S version = 1.11

Problem on apply:

```
* module.operations.module.kubernetes_cluster_operations.null_resource.initialize_storage_class: Error running command 'echo "kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain" | kubectl apply -f - --kubeconfig="./output/kubeconfig_eu-west-1-demo-test-ops"': exit status 1. Output: The StorageClass "gp2" is invalid: 
* parameters: Forbidden: updates to parameters are forbidden.
* reclaimPolicy: Forbidden: updates to reclaimPolicy are forbidden.
```
According to docs for EKS:
https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html
"Amazon EKS clusters that were created prior to Kubernetes version 1.11 were not created with any storage classes"

Possible solution is to make storage class inicialisation conditional or remove it for version of K8S >=1.11
